def get_fasta(access_id):
    import requests
    r = requests.get("http://www.uniprot.org/uniprot/{}.fasta".format(access_id))
    return ''.join(r.text.splitlines()[1:])

def find_motif(seq):
    import re
    return [1 + m.start(1) for m in re.finditer(r'(?=(N[^P][ST][^P]))', seq)]

def mprt(access_ids):
    return {a: find_motif(get_fasta(a)) for a in access_ids}

if __name__ == '__main__':
    assert get_fasta('B5ZC00') == \
    "MKNKFKTQEELVNHLKTVGFVFANSEIYNGLANAWDYGPLGVLLKNNLKNLWWKEFVTKQ" \
    "KDVVGLDSAIILNPLVWKASGHLDNFSDPLIDCKNCKARYRADKLIESFDENIHIAENSS" \
    "NEEFAKVLNDYEISCPTCKQFNWTEIRHFNLMFKTYQGVIEDAKNVVYLRPETAQGIFVN" \
    "FKNVQRSMRLHLPFGIAQIGKSFRNEITPGNFIFRTREFEQMEIEFFLKEESAYDIFDKY" \
    "LNQIENWLVSACGLSLNNLRKHEHPKEELSHYSKKTIDFEYNFLHGFSELYGIAYRTNYD" \
    "LSVHMNLSKKDLTYFDEQTKEKYVPHVIEPSVGVERLLYAILTEATFIEKLENDDERILM" \
    "DLKYDLAPYKIAVMPLVNKLKDKAEEIYGKILDLNISATFDNSGSIGKRYRRQDAIGTIY" \
    "CLTIDFDSLDDQQDPSFTIRERNSMAQKRIKLSELPLYLNQKAHEDFQRQCQK"

    assert find_motif( \
    "MKNKFKTQEELVNHLKTVGFVFANSEIYNGLANAWDYGPLGVLLKNNLKNLWWKEFVTKQ" \
    "KDVVGLDSAIILNPLVWKASGHLDNFSDPLIDCKNCKARYRADKLIESFDENIHIAENSS" \
    "NEEFAKVLNDYEISCPTCKQFNWTEIRHFNLMFKTYQGVIEDAKNVVYLRPETAQGIFVN" \
    "FKNVQRSMRLHLPFGIAQIGKSFRNEITPGNFIFRTREFEQMEIEFFLKEESAYDIFDKY" \
    "LNQIENWLVSACGLSLNNLRKHEHPKEELSHYSKKTIDFEYNFLHGFSELYGIAYRTNYD" \
    "LSVHMNLSKKDLTYFDEQTKEKYVPHVIEPSVGVERLLYAILTEATFIEKLENDDERILM" \
    "DLKYDLAPYKIAVMPLVNKLKDKAEEIYGKILDLNISATFDNSGSIGKRYRRQDAIGTIY" \
    "CLTIDFDSLDDQQDPSFTIRERNSMAQKRIKLSELPLYLNQKAHEDFQRQCQK") == [85, 118, 142, 306, 395]

    d = mprt(['A2Z669', 'B5ZC00', 'P07204_TRBM_HUMAN', 'P20840_SAG1_YEAST'])
    assert d['A2Z669'] == []
    assert d['B5ZC00'] == [85, 118, 142, 306, 395]
    assert d['P07204_TRBM_HUMAN'] == [47, 115, 116, 382, 409]
    assert d['P20840_SAG1_YEAST'] == [79, 109, 135, 248, 306, 348, 364, 402, 485, 501, 614]

    import sys
    if len(sys.argv) > 1:
        with open(sys.argv[1], 'r') as data_file:
            d = mprt(data_file.read().splitlines())
            for k, v in d.iteritems():
                if v:
                    print k
                    print ' '.join(str(s) for s in v)